GET http://localhost:3003/api/blogs

Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1MjNiZGUwNDU1NmVhM2NmMGRjM2Q1OCIsImlhdCI6MTY5Njk1NjQ5NH0._5nI9-N97g2vLRwS1cMBez7L5KB4mDtJfLXi_efOeTQ
